name: Merge

on:
  push:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:

  test_thing:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Display envvars
        run: env
